#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3308/bontechschema
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true

server:
    port: 8081
    servlet:
        context-path: /
limit:
    time : 12
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        username: root
        url: jdbc:mysql://localhost:3308/bontechschema
        maxPoolSize: 20
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                show_sql: true
                format_sql: true
                dialect:  org.hibernate.dialect.MySQLDialect
                #gnerate_statistics: false
                order_inserts: false




